### ISSUE TITLE
cannot read property 'contents' of undefined at object.Parser.parse

### ISSUE THREAD

**Issue by ayushbhardwaj** [gdupont/less-monitor#5]
It quit watching .less file itself whenever i m updated .less file with the following error shown in an image :
![ss1](https://cloud.githubusercontent.com/assets/534935/8372242/fb625bea-1bfe-11e5-9251-52b82ffcae8c.jpg)

**Comment by martinjarmar** [comment]
I had the same issue. It's because less-monitor does not work with less v2. Until this issue is fixed, the solution is to uninstall both less-monitor & less, and then install them again with downgraded version of less.
```
npm install -g less@1.7.5 less-monitor
```
Single command is needed. Otherwise latest less version will be downloaded as a less-monitor dependency. Hope this helps.

**Comment by ayushbhardwaj** [comment]
thanks martin :)

**Comment by graceman9** [comment]
Another solution can be to install them locally:

    npm init -y
    npm install less@1.7.5 less-monitor
    vim "+set ff=unix" "+wq" node_modules/less-monitor/bin/less-monitor

Last line in those 3 is related to the #2 

Usage:

    node_modules/less-monitor/bin/less-monitor
